# Generated by Django 3.0.3 on 2021-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('artical_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('artical_title', models.TextField()),
                ('artical_content', models.TextField()),
                ('artical_views', models.BigIntegerField(blank=True, default=0, null=True)),
                ('artical_comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('artical_like_count', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'artical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticalLabel',
            fields=[
                ('artical_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_id', models.IntegerField()),
            ],
            options={
                'db_table': 'artical_label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticalSort',
            fields=[
                ('artical_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sort_id', models.IntegerField()),
            ],
            options={
                'db_table': 'artical_sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('artical_id', models.IntegerField()),
                ('comment_like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_date', models.DateField(blank=True, default=0, null=True)),
                ('comment_content', models.TextField()),
                ('parent_comment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20)),
                ('label_alias', models.CharField(max_length=15)),
                ('label_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30)),
                ('user_profile_photo', models.CharField(max_length=255)),
                ('user_birthday', models.DateField(blank=True, null=True)),
                ('user_telephone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
